### PR TITLE
fix: always return a LogReturn instead of null

### PR DESCRIPTION
**Pull request by Keyrxng**
I'm tired of having to cast our `logMessage.diff` and optionally accessing our `LogReturn` objects from the logger

I have reversed the boolean logic here so that we log instead of returning null and so we can always return a `logReturn` object

### CODE REVIEW

**Comment by Keyrxng** [comment]
This should release just fine eh what you think?

**Comment by Keyrxng** [comment]
dont merge

**Comment by gentlementlegen** [comment]
This is actually a great update. Yes it should create a new version.

**Review by gentlementlegen — APPROVED** [review]

**Comment by Keyrxng** [comment]
> This is actually a great update. Yes it should create a new version.

It felt wrong going with an empty commit so I found something worth the hassle of it all hahaha

**Pull request merged**
